name: continuous-integration
on: [pull_request]
jobs:
  setup-environment:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    - name: Install prerequisites
      run: | 
       sudo apt-get install -y build-essential libxi-dev libglu1-mesa-dev libglew-dev pkg-config libglu1-mesa-dev freeglut3-dev mesa-common-dev libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev  xserver-xorg-dev libxext-dev g++-4.8 xvfb
       export DISPLAY=':99.0' # for tape-run 
       Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & # for tape-run 
    - run: npm run setup

  base-tests:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "Base istanbul/tape node tests"
      run: npm test

  benchmark-tests:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "Benchmark tests"
      run: npm run benchmark

  gif-tests:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "Gif tests"
      run: npm run gif-test

  browserify-core-tests:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "Browserify core tests and run"
      run: grunt tests && npm run core-tests

  jsmine-ui-tests:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "Jasmine UI tests (mocked browser env)"
      run: npm run test-ui

  jest-ui-tests:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "jest-puppeteer UI tests (full browser env)"
      run: npm run test-ui-2    

  cli-tests:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "CLI tests"
      run: npm run test-cli

  grunt-build-test:
    runs-on: ubuntu-18.04
    needs: setup-environment
    steps:
    - name: "Grunt build test of dev environment"
      run: grunt build

## Cache NPM folder
# cache:
#   directories:
#     - ~/.npm
#     - ~/.cache
